/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;


/**
 * 用户账户表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAccount extends Serializable {

	/**
	 * Setter for <code>blog.tb_account.id</code>. 主键
	 */
	public void setId(ULong value);

	/**
	 * Getter for <code>blog.tb_account.id</code>. 主键
	 */
	@NotNull
	public ULong getId();

	/**
	 * Setter for <code>blog.tb_account.user_id</code>. 用户id
	 */
	public void setUserId(Long value);

	/**
	 * Getter for <code>blog.tb_account.user_id</code>. 用户id
	 */
	@NotNull
	public Long getUserId();

	/**
	 * Setter for <code>blog.tb_account.account_name</code>. 登录帐号
	 */
	public void setAccountName(String value);

	/**
	 * Getter for <code>blog.tb_account.account_name</code>. 登录帐号
	 */
	@NotNull
	@Size(max = 30)
	public String getAccountName();

	/**
	 * Setter for <code>blog.tb_account.telephone</code>. 电话
	 */
	public void setTelephone(String value);

	/**
	 * Getter for <code>blog.tb_account.telephone</code>. 电话
	 */
	@NotNull
	@Size(max = 15)
	public String getTelephone();

	/**
	 * Setter for <code>blog.tb_account.email</code>. 点子邮箱
	 */
	public void setEmail(String value);

	/**
	 * Getter for <code>blog.tb_account.email</code>. 点子邮箱
	 */
	@NotNull
	@Size(max = 20)
	public String getEmail();

	/**
	 * Setter for <code>blog.tb_account.password</code>. 密码
	 */
	public void setPassword(String value);

	/**
	 * Getter for <code>blog.tb_account.password</code>. 密码
	 */
	@NotNull
	@Size(max = 20)
	public String getPassword();

	/**
	 * Setter for <code>blog.tb_account.type</code>. 账户类型，0:普通用户，1:管理员
	 */
	public void setType(Byte value);

	/**
	 * Getter for <code>blog.tb_account.type</code>. 账户类型，0:普通用户，1:管理员
	 */
	@NotNull
	public Byte getType();

	/**
	 * Setter for <code>blog.tb_account.created_time</code>.
	 */
	public void setCreatedTime(Timestamp value);

	/**
	 * Getter for <code>blog.tb_account.created_time</code>.
	 */
	@NotNull
	public Timestamp getCreatedTime();

	/**
	 * Setter for <code>blog.tb_account.updated_time</code>.
	 */
	public void setUpdatedTime(Timestamp value);

	/**
	 * Getter for <code>blog.tb_account.updated_time</code>.
	 */
	@NotNull
	public Timestamp getUpdatedTime();

	/**
	 * Setter for <code>blog.tb_account.status</code>. 账户状态，枚举类型，0:无效，1:有效，默认为1
	 */
	public void setStatus(Byte value);

	/**
	 * Getter for <code>blog.tb_account.status</code>. 账户状态，枚举类型，0:无效，1:有效，默认为1
	 */
	@NotNull
	public Byte getStatus();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IAccount
	 */
	public void from(org.yanlz.blog.db.tables.interfaces.IAccount from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IAccount
	 */
	public <E extends org.yanlz.blog.db.tables.interfaces.IAccount> E into(E into);
}
