/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;


/**
 * 文章信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbBlogInfo extends Serializable {

	/**
	 * Setter for <code>blog.tb_blog_info.blog_id</code>. 主键
	 */
	public void setBlogId(ULong value);

	/**
	 * Getter for <code>blog.tb_blog_info.blog_id</code>. 主键
	 */
	@NotNull
	public ULong getBlogId();

	/**
	 * Setter for <code>blog.tb_blog_info.blog_author</code>. 用户ID
	 */
	public void setBlogAuthor(Long value);

	/**
	 * Getter for <code>blog.tb_blog_info.blog_author</code>. 用户ID
	 */
	@NotNull
	public Long getBlogAuthor();

	/**
	 * Setter for <code>blog.tb_blog_info.blog_type</code>. 博客类型，0：未分类
	 */
	public void setBlogType(Byte value);

	/**
	 * Getter for <code>blog.tb_blog_info.blog_type</code>. 博客类型，0：未分类
	 */
	@NotNull
	public Byte getBlogType();

	/**
	 * Setter for <code>blog.tb_blog_info.blog_title</code>. 文章标题
	 */
	public void setBlogTitle(String value);

	/**
	 * Getter for <code>blog.tb_blog_info.blog_title</code>. 文章标题
	 */
	@NotNull
	@Size(max = 200)
	public String getBlogTitle();

	/**
	 * Setter for <code>blog.tb_blog_info.blog_abstract</code>. 文章摘要
	 */
	public void setBlogAbstract(String value);

	/**
	 * Getter for <code>blog.tb_blog_info.blog_abstract</code>. 文章摘要
	 */
	@NotNull
	@Size(max = 500)
	public String getBlogAbstract();

	/**
	 * Setter for <code>blog.tb_blog_info.blog_content</code>. 文章内容
	 */
	public void setBlogContent(String value);

	/**
	 * Getter for <code>blog.tb_blog_info.blog_content</code>. 文章内容
	 */
	@NotNull
	public String getBlogContent();

	/**
	 * Setter for <code>blog.tb_blog_info.created_time</code>. 创建时间
	 */
	public void setCreatedTime(Timestamp value);

	/**
	 * Getter for <code>blog.tb_blog_info.created_time</code>. 创建时间
	 */
	@NotNull
	public Timestamp getCreatedTime();

	/**
	 * Setter for <code>blog.tb_blog_info.updated_time</code>. 更新时间
	 */
	public void setUpdatedTime(Timestamp value);

	/**
	 * Getter for <code>blog.tb_blog_info.updated_time</code>. 更新时间
	 */
	@NotNull
	public Timestamp getUpdatedTime();

	/**
	 * Setter for <code>blog.tb_blog_info.comment_count</code>. 评论条数
	 */
	public void setCommentCount(Long value);

	/**
	 * Getter for <code>blog.tb_blog_info.comment_count</code>. 评论条数
	 */
	public Long getCommentCount();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ITbBlogInfo
	 */
	public void from(org.yanlz.blog.db.tables.interfaces.ITbBlogInfo from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ITbBlogInfo
	 */
	public <E extends org.yanlz.blog.db.tables.interfaces.ITbBlogInfo> E into(E into);
}
