/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;


/**
 * 评论信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbCommentInfo extends Serializable {

	/**
	 * Setter for <code>blog.tb_comment_info.comment_id</code>. 主键
	 */
	public void setCommentId(ULong value);

	/**
	 * Getter for <code>blog.tb_comment_info.comment_id</code>. 主键
	 */
	@NotNull
	public ULong getCommentId();

	/**
	 * Setter for <code>blog.tb_comment_info.comment_blog_id</code>. 评论文章ID
	 */
	public void setCommentBlogId(Long value);

	/**
	 * Getter for <code>blog.tb_comment_info.comment_blog_id</code>. 评论文章ID
	 */
	@NotNull
	public Long getCommentBlogId();

	/**
	 * Setter for <code>blog.tb_comment_info.comment_user_id</code>. 评论人id
	 */
	public void setCommentUserId(Long value);

	/**
	 * Getter for <code>blog.tb_comment_info.comment_user_id</code>. 评论人id
	 */
	@NotNull
	public Long getCommentUserId();

	/**
	 * Setter for <code>blog.tb_comment_info.comment_content</code>. 评论内容
	 */
	public void setCommentContent(String value);

	/**
	 * Getter for <code>blog.tb_comment_info.comment_content</code>. 评论内容
	 */
	@NotNull
	@Size(max = 65535)
	public String getCommentContent();

	/**
	 * Setter for <code>blog.tb_comment_info.parent_id</code>. 评论父节点
	 */
	public void setParentId(Long value);

	/**
	 * Getter for <code>blog.tb_comment_info.parent_id</code>. 评论父节点
	 */
	public Long getParentId();

	/**
	 * Setter for <code>blog.tb_comment_info.created_time</code>. 评论时间
	 */
	public void setCreatedTime(Timestamp value);

	/**
	 * Getter for <code>blog.tb_comment_info.created_time</code>. 评论时间
	 */
	@NotNull
	public Timestamp getCreatedTime();

	/**
	 * Setter for <code>blog.tb_comment_info.updated_time</code>. 更新时间
	 */
	public void setUpdatedTime(Timestamp value);

	/**
	 * Getter for <code>blog.tb_comment_info.updated_time</code>. 更新时间
	 */
	@NotNull
	public Timestamp getUpdatedTime();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ITbCommentInfo
	 */
	public void from(org.yanlz.blog.db.tables.interfaces.ITbCommentInfo from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ITbCommentInfo
	 */
	public <E extends org.yanlz.blog.db.tables.interfaces.ITbCommentInfo> E into(E into);
}
