/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;


/**
 * 用户基本信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserInfo extends Serializable {

	/**
	 * Setter for <code>blog.tb_user_info.user_id</code>. 主键
	 */
	public void setUserId(ULong value);

	/**
	 * Getter for <code>blog.tb_user_info.user_id</code>. 主键
	 */
	@NotNull
	public ULong getUserId();

	/**
	 * Setter for <code>blog.tb_user_info.nick_name</code>. 用户昵称
	 */
	public void setNickName(String value);

	/**
	 * Getter for <code>blog.tb_user_info.nick_name</code>. 用户昵称
	 */
	@NotNull
	@Size(max = 30)
	public String getNickName();

	/**
	 * Setter for <code>blog.tb_user_info.protrait_url</code>. 头像地址
	 */
	public void setProtraitUrl(String value);

	/**
	 * Getter for <code>blog.tb_user_info.protrait_url</code>. 头像地址
	 */
	@NotNull
	@Size(max = 200)
	public String getProtraitUrl();

	/**
	 * Setter for <code>blog.tb_user_info.telephone</code>. 电话
	 */
	public void setTelephone(String value);

	/**
	 * Getter for <code>blog.tb_user_info.telephone</code>. 电话
	 */
	@NotNull
	@Size(max = 15)
	public String getTelephone();

	/**
	 * Setter for <code>blog.tb_user_info.created_time</code>. 创建时间
	 */
	public void setCreatedTime(Timestamp value);

	/**
	 * Getter for <code>blog.tb_user_info.created_time</code>. 创建时间
	 */
	@NotNull
	public Timestamp getCreatedTime();

	/**
	 * Setter for <code>blog.tb_user_info.updated_time</code>. 修改时间
	 */
	public void setUpdatedTime(Timestamp value);

	/**
	 * Getter for <code>blog.tb_user_info.updated_time</code>. 修改时间
	 */
	@NotNull
	public Timestamp getUpdatedTime();

	/**
	 * Setter for <code>blog.tb_user_info.status</code>. 账户状态，枚举类型，0:无效，1:有效，默认为1
	 */
	public void setStatus(Byte value);

	/**
	 * Getter for <code>blog.tb_user_info.status</code>. 账户状态，枚举类型，0:无效，1:有效，默认为1
	 */
	@NotNull
	public Byte getStatus();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IUserInfo
	 */
	public void from(org.yanlz.blog.db.tables.interfaces.IUserInfo from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IUserInfo
	 */
	public <E extends org.yanlz.blog.db.tables.interfaces.IUserInfo> E into(E into);
}
