/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.interfaces.ICommentInfo;


/**
 * 评论信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentInfo implements ICommentInfo {

	private static final long serialVersionUID = 856640695;

	private ULong     commentId;
	private Long      commentBlogId;
	private Long      commentUserId;
	private String    commentContent;
	private Long      parentId;
	private Timestamp createdTime;
	private Timestamp updatedTime;

	public CommentInfo() {}

	public CommentInfo(CommentInfo value) {
		this.commentId = value.commentId;
		this.commentBlogId = value.commentBlogId;
		this.commentUserId = value.commentUserId;
		this.commentContent = value.commentContent;
		this.parentId = value.parentId;
		this.createdTime = value.createdTime;
		this.updatedTime = value.updatedTime;
	}

	public CommentInfo(
		ULong     commentId,
		Long      commentBlogId,
		Long      commentUserId,
		String    commentContent,
		Long      parentId,
		Timestamp createdTime,
		Timestamp updatedTime
	) {
		this.commentId = commentId;
		this.commentBlogId = commentBlogId;
		this.commentUserId = commentUserId;
		this.commentContent = commentContent;
		this.parentId = parentId;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	@NotNull
	@Override
	public ULong getCommentId() {
		return this.commentId;
	}

	@Override
	public void setCommentId(ULong commentId) {
		this.commentId = commentId;
	}

	@NotNull
	@Override
	public Long getCommentBlogId() {
		return this.commentBlogId;
	}

	@Override
	public void setCommentBlogId(Long commentBlogId) {
		this.commentBlogId = commentBlogId;
	}

	@NotNull
	@Override
	public Long getCommentUserId() {
		return this.commentUserId;
	}

	@Override
	public void setCommentUserId(Long commentUserId) {
		this.commentUserId = commentUserId;
	}

	@NotNull
	@Size(max = 65535)
	@Override
	public String getCommentContent() {
		return this.commentContent;
	}

	@Override
	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	@Override
	public Long getParentId() {
		return this.parentId;
	}

	@Override
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@NotNull
	@Override
	public Timestamp getCreatedTime() {
		return this.createdTime;
	}

	@Override
	public void setCreatedTime(Timestamp createdTime) {
		this.createdTime = createdTime;
	}

	@NotNull
	@Override
	public Timestamp getUpdatedTime() {
		return this.updatedTime;
	}

	@Override
	public void setUpdatedTime(Timestamp updatedTime) {
		this.updatedTime = updatedTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CommentInfo (");

		sb.append(commentId);
		sb.append(", ").append(commentBlogId);
		sb.append(", ").append(commentUserId);
		sb.append(", ").append(commentContent);
		sb.append(", ").append(parentId);
		sb.append(", ").append(createdTime);
		sb.append(", ").append(updatedTime);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ICommentInfo from) {
		setCommentId(from.getCommentId());
		setCommentBlogId(from.getCommentBlogId());
		setCommentUserId(from.getCommentUserId());
		setCommentContent(from.getCommentContent());
		setParentId(from.getParentId());
		setCreatedTime(from.getCreatedTime());
		setUpdatedTime(from.getUpdatedTime());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ICommentInfo> E into(E into) {
		into.from(this);
		return into;
	}
}
