/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.interfaces.ITbAccount;


/**
 * 用户账户表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbAccount implements ITbAccount {

	private static final long serialVersionUID = 740008014;

	private ULong     id;
	private Long      userId;
	private String    accountName;
	private String    telephone;
	private String    email;
	private String    password;
	private Byte      type;
	private Timestamp createdTime;
	private Timestamp updatedTime;
	private Byte      status;

	public TbAccount() {}

	public TbAccount(TbAccount value) {
		this.id = value.id;
		this.userId = value.userId;
		this.accountName = value.accountName;
		this.telephone = value.telephone;
		this.email = value.email;
		this.password = value.password;
		this.type = value.type;
		this.createdTime = value.createdTime;
		this.updatedTime = value.updatedTime;
		this.status = value.status;
	}

	public TbAccount(
		ULong     id,
		Long      userId,
		String    accountName,
		String    telephone,
		String    email,
		String    password,
		Byte      type,
		Timestamp createdTime,
		Timestamp updatedTime,
		Byte      status
	) {
		this.id = id;
		this.userId = userId;
		this.accountName = accountName;
		this.telephone = telephone;
		this.email = email;
		this.password = password;
		this.type = type;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.status = status;
	}

	@NotNull
	@Override
	public ULong getId() {
		return this.id;
	}

	@Override
	public void setId(ULong id) {
		this.id = id;
	}

	@NotNull
	@Override
	public Long getUserId() {
		return this.userId;
	}

	@Override
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@NotNull
	@Size(max = 30)
	@Override
	public String getAccountName() {
		return this.accountName;
	}

	@Override
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@NotNull
	@Size(max = 15)
	@Override
	public String getTelephone() {
		return this.telephone;
	}

	@Override
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@NotNull
	@Size(max = 20)
	@Override
	public String getEmail() {
		return this.email;
	}

	@Override
	public void setEmail(String email) {
		this.email = email;
	}

	@NotNull
	@Size(max = 20)
	@Override
	public String getPassword() {
		return this.password;
	}

	@Override
	public void setPassword(String password) {
		this.password = password;
	}

	@NotNull
	@Override
	public Byte getType() {
		return this.type;
	}

	@Override
	public void setType(Byte type) {
		this.type = type;
	}

	@NotNull
	@Override
	public Timestamp getCreatedTime() {
		return this.createdTime;
	}

	@Override
	public void setCreatedTime(Timestamp createdTime) {
		this.createdTime = createdTime;
	}

	@NotNull
	@Override
	public Timestamp getUpdatedTime() {
		return this.updatedTime;
	}

	@Override
	public void setUpdatedTime(Timestamp updatedTime) {
		this.updatedTime = updatedTime;
	}

	@NotNull
	@Override
	public Byte getStatus() {
		return this.status;
	}

	@Override
	public void setStatus(Byte status) {
		this.status = status;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("TbAccount (");

		sb.append(id);
		sb.append(", ").append(userId);
		sb.append(", ").append(accountName);
		sb.append(", ").append(telephone);
		sb.append(", ").append(email);
		sb.append(", ").append(password);
		sb.append(", ").append(type);
		sb.append(", ").append(createdTime);
		sb.append(", ").append(updatedTime);
		sb.append(", ").append(status);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ITbAccount from) {
		setId(from.getId());
		setUserId(from.getUserId());
		setAccountName(from.getAccountName());
		setTelephone(from.getTelephone());
		setEmail(from.getEmail());
		setPassword(from.getPassword());
		setType(from.getType());
		setCreatedTime(from.getCreatedTime());
		setUpdatedTime(from.getUpdatedTime());
		setStatus(from.getStatus());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ITbAccount> E into(E into) {
		into.from(this);
		return into;
	}
}
