/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.interfaces.IUserInfo;


/**
 * 用户基本信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo implements IUserInfo {

	private static final long serialVersionUID = 1870067800;

	private ULong     userId;
	private String    nickName;
	private String    protraitUrl;
	private String    telephone;
	private Timestamp createdTime;
	private Timestamp updatedTime;
	private Byte      status;

	public UserInfo() {}

	public UserInfo(UserInfo value) {
		this.userId = value.userId;
		this.nickName = value.nickName;
		this.protraitUrl = value.protraitUrl;
		this.telephone = value.telephone;
		this.createdTime = value.createdTime;
		this.updatedTime = value.updatedTime;
		this.status = value.status;
	}

	public UserInfo(
		ULong     userId,
		String    nickName,
		String    protraitUrl,
		String    telephone,
		Timestamp createdTime,
		Timestamp updatedTime,
		Byte      status
	) {
		this.userId = userId;
		this.nickName = nickName;
		this.protraitUrl = protraitUrl;
		this.telephone = telephone;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.status = status;
	}

	@NotNull
	@Override
	public ULong getUserId() {
		return this.userId;
	}

	@Override
	public void setUserId(ULong userId) {
		this.userId = userId;
	}

	@NotNull
	@Size(max = 30)
	@Override
	public String getNickName() {
		return this.nickName;
	}

	@Override
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@NotNull
	@Size(max = 200)
	@Override
	public String getProtraitUrl() {
		return this.protraitUrl;
	}

	@Override
	public void setProtraitUrl(String protraitUrl) {
		this.protraitUrl = protraitUrl;
	}

	@NotNull
	@Size(max = 15)
	@Override
	public String getTelephone() {
		return this.telephone;
	}

	@Override
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@NotNull
	@Override
	public Timestamp getCreatedTime() {
		return this.createdTime;
	}

	@Override
	public void setCreatedTime(Timestamp createdTime) {
		this.createdTime = createdTime;
	}

	@NotNull
	@Override
	public Timestamp getUpdatedTime() {
		return this.updatedTime;
	}

	@Override
	public void setUpdatedTime(Timestamp updatedTime) {
		this.updatedTime = updatedTime;
	}

	@NotNull
	@Override
	public Byte getStatus() {
		return this.status;
	}

	@Override
	public void setStatus(Byte status) {
		this.status = status;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("UserInfo (");

		sb.append(userId);
		sb.append(", ").append(nickName);
		sb.append(", ").append(protraitUrl);
		sb.append(", ").append(telephone);
		sb.append(", ").append(createdTime);
		sb.append(", ").append(updatedTime);
		sb.append(", ").append(status);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IUserInfo from) {
		setUserId(from.getUserId());
		setNickName(from.getNickName());
		setProtraitUrl(from.getProtraitUrl());
		setTelephone(from.getTelephone());
		setCreatedTime(from.getCreatedTime());
		setUpdatedTime(from.getUpdatedTime());
		setStatus(from.getStatus());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IUserInfo> E into(E into) {
		into.from(this);
		return into;
	}
}
