/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.Account;
import org.yanlz.blog.db.tables.records.AccountRecord;


/**
 * 用户账户表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountDao extends DAOImpl<AccountRecord, org.yanlz.blog.db.tables.pojos.Account, ULong> {

	/**
	 * Create a new AccountDao without any configuration
	 */
	public AccountDao() {
		super(Account.TB_ACCOUNT, org.yanlz.blog.db.tables.pojos.Account.class);
	}

	/**
	 * Create a new AccountDao with an attached configuration
	 */
	public AccountDao(Configuration configuration) {
		super(Account.TB_ACCOUNT, org.yanlz.blog.db.tables.pojos.Account.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ULong getId(org.yanlz.blog.db.tables.pojos.Account object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchById(ULong... values) {
		return fetch(Account.TB_ACCOUNT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.yanlz.blog.db.tables.pojos.Account fetchOneById(ULong value) {
		return fetchOne(Account.TB_ACCOUNT.ID, value);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchByUserId(Long... values) {
		return fetch(Account.TB_ACCOUNT.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>account_name IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchByAccountName(String... values) {
		return fetch(Account.TB_ACCOUNT.ACCOUNT_NAME, values);
	}

	/**
	 * Fetch records that have <code>telephone IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchByTelephone(String... values) {
		return fetch(Account.TB_ACCOUNT.TELEPHONE, values);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchByEmail(String... values) {
		return fetch(Account.TB_ACCOUNT.EMAIL, values);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchByPassword(String... values) {
		return fetch(Account.TB_ACCOUNT.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchByType(Byte... values) {
		return fetch(Account.TB_ACCOUNT.TYPE, values);
	}

	/**
	 * Fetch records that have <code>created_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchByCreatedTime(Timestamp... values) {
		return fetch(Account.TB_ACCOUNT.CREATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>updated_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchByUpdatedTime(Timestamp... values) {
		return fetch(Account.TB_ACCOUNT.UPDATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.Account> fetchByStatus(Byte... values) {
		return fetch(Account.TB_ACCOUNT.STATUS, values);
	}
}
