/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.CommentInfo;
import org.yanlz.blog.db.tables.records.CommentInfoRecord;


/**
 * 评论信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentInfoDao extends DAOImpl<CommentInfoRecord, org.yanlz.blog.db.tables.pojos.CommentInfo, ULong> {

	/**
	 * Create a new CommentInfoDao without any configuration
	 */
	public CommentInfoDao() {
		super(CommentInfo.TB_COMMENT_INFO, org.yanlz.blog.db.tables.pojos.CommentInfo.class);
	}

	/**
	 * Create a new CommentInfoDao with an attached configuration
	 */
	public CommentInfoDao(Configuration configuration) {
		super(CommentInfo.TB_COMMENT_INFO, org.yanlz.blog.db.tables.pojos.CommentInfo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ULong getId(org.yanlz.blog.db.tables.pojos.CommentInfo object) {
		return object.getCommentId();
	}

	/**
	 * Fetch records that have <code>comment_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.CommentInfo> fetchByCommentId(ULong... values) {
		return fetch(CommentInfo.TB_COMMENT_INFO.COMMENT_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>comment_id = value</code>
	 */
	public org.yanlz.blog.db.tables.pojos.CommentInfo fetchOneByCommentId(ULong value) {
		return fetchOne(CommentInfo.TB_COMMENT_INFO.COMMENT_ID, value);
	}

	/**
	 * Fetch records that have <code>comment_blog_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.CommentInfo> fetchByCommentBlogId(Long... values) {
		return fetch(CommentInfo.TB_COMMENT_INFO.COMMENT_BLOG_ID, values);
	}

	/**
	 * Fetch records that have <code>comment_user_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.CommentInfo> fetchByCommentUserId(Long... values) {
		return fetch(CommentInfo.TB_COMMENT_INFO.COMMENT_USER_ID, values);
	}

	/**
	 * Fetch records that have <code>comment_content IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.CommentInfo> fetchByCommentContent(String... values) {
		return fetch(CommentInfo.TB_COMMENT_INFO.COMMENT_CONTENT, values);
	}

	/**
	 * Fetch records that have <code>parent_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.CommentInfo> fetchByParentId(Long... values) {
		return fetch(CommentInfo.TB_COMMENT_INFO.PARENT_ID, values);
	}

	/**
	 * Fetch records that have <code>created_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.CommentInfo> fetchByCreatedTime(Timestamp... values) {
		return fetch(CommentInfo.TB_COMMENT_INFO.CREATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>updated_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.CommentInfo> fetchByUpdatedTime(Timestamp... values) {
		return fetch(CommentInfo.TB_COMMENT_INFO.UPDATED_TIME, values);
	}
}
