/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.TbAccount;
import org.yanlz.blog.db.tables.records.TbAccountRecord;


/**
 * 用户账户表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbAccountDao extends DAOImpl<TbAccountRecord, org.yanlz.blog.db.tables.pojos.TbAccount, ULong> {

	/**
	 * Create a new TbAccountDao without any configuration
	 */
	public TbAccountDao() {
		super(TbAccount.TB_ACCOUNT, org.yanlz.blog.db.tables.pojos.TbAccount.class);
	}

	/**
	 * Create a new TbAccountDao with an attached configuration
	 */
	public TbAccountDao(Configuration configuration) {
		super(TbAccount.TB_ACCOUNT, org.yanlz.blog.db.tables.pojos.TbAccount.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ULong getId(org.yanlz.blog.db.tables.pojos.TbAccount object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchById(ULong... values) {
		return fetch(TbAccount.TB_ACCOUNT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.yanlz.blog.db.tables.pojos.TbAccount fetchOneById(ULong value) {
		return fetchOne(TbAccount.TB_ACCOUNT.ID, value);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchByUserId(Long... values) {
		return fetch(TbAccount.TB_ACCOUNT.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>account_name IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchByAccountName(String... values) {
		return fetch(TbAccount.TB_ACCOUNT.ACCOUNT_NAME, values);
	}

	/**
	 * Fetch records that have <code>telephone IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchByTelephone(String... values) {
		return fetch(TbAccount.TB_ACCOUNT.TELEPHONE, values);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchByEmail(String... values) {
		return fetch(TbAccount.TB_ACCOUNT.EMAIL, values);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchByPassword(String... values) {
		return fetch(TbAccount.TB_ACCOUNT.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchByType(Byte... values) {
		return fetch(TbAccount.TB_ACCOUNT.TYPE, values);
	}

	/**
	 * Fetch records that have <code>created_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchByCreatedTime(Timestamp... values) {
		return fetch(TbAccount.TB_ACCOUNT.CREATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>updated_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchByUpdatedTime(Timestamp... values) {
		return fetch(TbAccount.TB_ACCOUNT.UPDATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbAccount> fetchByStatus(Byte... values) {
		return fetch(TbAccount.TB_ACCOUNT.STATUS, values);
	}
}
