/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.TbBlogInfo;
import org.yanlz.blog.db.tables.records.TbBlogInfoRecord;


/**
 * 文章信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbBlogInfoDao extends DAOImpl<TbBlogInfoRecord, org.yanlz.blog.db.tables.pojos.TbBlogInfo, ULong> {

	/**
	 * Create a new TbBlogInfoDao without any configuration
	 */
	public TbBlogInfoDao() {
		super(TbBlogInfo.TB_BLOG_INFO, org.yanlz.blog.db.tables.pojos.TbBlogInfo.class);
	}

	/**
	 * Create a new TbBlogInfoDao with an attached configuration
	 */
	public TbBlogInfoDao(Configuration configuration) {
		super(TbBlogInfo.TB_BLOG_INFO, org.yanlz.blog.db.tables.pojos.TbBlogInfo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ULong getId(org.yanlz.blog.db.tables.pojos.TbBlogInfo object) {
		return object.getBlogId();
	}

	/**
	 * Fetch records that have <code>blog_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbBlogInfo> fetchByBlogId(ULong... values) {
		return fetch(TbBlogInfo.TB_BLOG_INFO.BLOG_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>blog_id = value</code>
	 */
	public org.yanlz.blog.db.tables.pojos.TbBlogInfo fetchOneByBlogId(ULong value) {
		return fetchOne(TbBlogInfo.TB_BLOG_INFO.BLOG_ID, value);
	}

	/**
	 * Fetch records that have <code>blog_author IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbBlogInfo> fetchByBlogAuthor(Long... values) {
		return fetch(TbBlogInfo.TB_BLOG_INFO.BLOG_AUTHOR, values);
	}

	/**
	 * Fetch records that have <code>blog_type IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbBlogInfo> fetchByBlogType(Byte... values) {
		return fetch(TbBlogInfo.TB_BLOG_INFO.BLOG_TYPE, values);
	}

	/**
	 * Fetch records that have <code>blog_title IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbBlogInfo> fetchByBlogTitle(String... values) {
		return fetch(TbBlogInfo.TB_BLOG_INFO.BLOG_TITLE, values);
	}

	/**
	 * Fetch records that have <code>blog_abstract IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbBlogInfo> fetchByBlogAbstract(String... values) {
		return fetch(TbBlogInfo.TB_BLOG_INFO.BLOG_ABSTRACT, values);
	}

	/**
	 * Fetch records that have <code>blog_content IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbBlogInfo> fetchByBlogContent(String... values) {
		return fetch(TbBlogInfo.TB_BLOG_INFO.BLOG_CONTENT, values);
	}

	/**
	 * Fetch records that have <code>created_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbBlogInfo> fetchByCreatedTime(Timestamp... values) {
		return fetch(TbBlogInfo.TB_BLOG_INFO.CREATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>updated_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbBlogInfo> fetchByUpdatedTime(Timestamp... values) {
		return fetch(TbBlogInfo.TB_BLOG_INFO.UPDATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>comment_count IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbBlogInfo> fetchByCommentCount(Long... values) {
		return fetch(TbBlogInfo.TB_BLOG_INFO.COMMENT_COUNT, values);
	}
}
