/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.TbCommentInfo;
import org.yanlz.blog.db.tables.records.TbCommentInfoRecord;


/**
 * 评论信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCommentInfoDao extends DAOImpl<TbCommentInfoRecord, org.yanlz.blog.db.tables.pojos.TbCommentInfo, ULong> {

	/**
	 * Create a new TbCommentInfoDao without any configuration
	 */
	public TbCommentInfoDao() {
		super(TbCommentInfo.TB_COMMENT_INFO, org.yanlz.blog.db.tables.pojos.TbCommentInfo.class);
	}

	/**
	 * Create a new TbCommentInfoDao with an attached configuration
	 */
	public TbCommentInfoDao(Configuration configuration) {
		super(TbCommentInfo.TB_COMMENT_INFO, org.yanlz.blog.db.tables.pojos.TbCommentInfo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ULong getId(org.yanlz.blog.db.tables.pojos.TbCommentInfo object) {
		return object.getCommentId();
	}

	/**
	 * Fetch records that have <code>comment_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbCommentInfo> fetchByCommentId(ULong... values) {
		return fetch(TbCommentInfo.TB_COMMENT_INFO.COMMENT_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>comment_id = value</code>
	 */
	public org.yanlz.blog.db.tables.pojos.TbCommentInfo fetchOneByCommentId(ULong value) {
		return fetchOne(TbCommentInfo.TB_COMMENT_INFO.COMMENT_ID, value);
	}

	/**
	 * Fetch records that have <code>comment_blog_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbCommentInfo> fetchByCommentBlogId(Long... values) {
		return fetch(TbCommentInfo.TB_COMMENT_INFO.COMMENT_BLOG_ID, values);
	}

	/**
	 * Fetch records that have <code>comment_user_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbCommentInfo> fetchByCommentUserId(Long... values) {
		return fetch(TbCommentInfo.TB_COMMENT_INFO.COMMENT_USER_ID, values);
	}

	/**
	 * Fetch records that have <code>comment_content IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbCommentInfo> fetchByCommentContent(String... values) {
		return fetch(TbCommentInfo.TB_COMMENT_INFO.COMMENT_CONTENT, values);
	}

	/**
	 * Fetch records that have <code>parent_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbCommentInfo> fetchByParentId(Long... values) {
		return fetch(TbCommentInfo.TB_COMMENT_INFO.PARENT_ID, values);
	}

	/**
	 * Fetch records that have <code>created_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbCommentInfo> fetchByCreatedTime(Timestamp... values) {
		return fetch(TbCommentInfo.TB_COMMENT_INFO.CREATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>updated_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbCommentInfo> fetchByUpdatedTime(Timestamp... values) {
		return fetch(TbCommentInfo.TB_COMMENT_INFO.UPDATED_TIME, values);
	}
}
