/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.TbUserInfo;
import org.yanlz.blog.db.tables.records.TbUserInfoRecord;


/**
 * 用户基本信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbUserInfoDao extends DAOImpl<TbUserInfoRecord, org.yanlz.blog.db.tables.pojos.TbUserInfo, ULong> {

	/**
	 * Create a new TbUserInfoDao without any configuration
	 */
	public TbUserInfoDao() {
		super(TbUserInfo.TB_USER_INFO, org.yanlz.blog.db.tables.pojos.TbUserInfo.class);
	}

	/**
	 * Create a new TbUserInfoDao with an attached configuration
	 */
	public TbUserInfoDao(Configuration configuration) {
		super(TbUserInfo.TB_USER_INFO, org.yanlz.blog.db.tables.pojos.TbUserInfo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ULong getId(org.yanlz.blog.db.tables.pojos.TbUserInfo object) {
		return object.getUserId();
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbUserInfo> fetchByUserId(ULong... values) {
		return fetch(TbUserInfo.TB_USER_INFO.USER_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>user_id = value</code>
	 */
	public org.yanlz.blog.db.tables.pojos.TbUserInfo fetchOneByUserId(ULong value) {
		return fetchOne(TbUserInfo.TB_USER_INFO.USER_ID, value);
	}

	/**
	 * Fetch records that have <code>nick_name IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbUserInfo> fetchByNickName(String... values) {
		return fetch(TbUserInfo.TB_USER_INFO.NICK_NAME, values);
	}

	/**
	 * Fetch records that have <code>protrait_url IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbUserInfo> fetchByProtraitUrl(String... values) {
		return fetch(TbUserInfo.TB_USER_INFO.PROTRAIT_URL, values);
	}

	/**
	 * Fetch records that have <code>telephone IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbUserInfo> fetchByTelephone(String... values) {
		return fetch(TbUserInfo.TB_USER_INFO.TELEPHONE, values);
	}

	/**
	 * Fetch records that have <code>created_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbUserInfo> fetchByCreatedTime(Timestamp... values) {
		return fetch(TbUserInfo.TB_USER_INFO.CREATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>updated_time IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbUserInfo> fetchByUpdatedTime(Timestamp... values) {
		return fetch(TbUserInfo.TB_USER_INFO.UPDATED_TIME, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public List<org.yanlz.blog.db.tables.pojos.TbUserInfo> fetchByStatus(Byte... values) {
		return fetch(TbUserInfo.TB_USER_INFO.STATUS, values);
	}
}
