/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.TbBlogInfo;
import org.yanlz.blog.db.tables.interfaces.ITbBlogInfo;


/**
 * 文章信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbBlogInfoRecord extends UpdatableRecordImpl<TbBlogInfoRecord> implements Record9<ULong, Long, Byte, String, String, String, Timestamp, Timestamp, Long>, ITbBlogInfo {

	private static final long serialVersionUID = -788991466;

	/**
	 * Setter for <code>blog.tb_blog_info.blog_id</code>. 主键
	 */
	@Override
	public void setBlogId(ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>blog.tb_blog_info.blog_id</code>. 主键
	 */
	@NotNull
	@Override
	public ULong getBlogId() {
		return (ULong) getValue(0);
	}

	/**
	 * Setter for <code>blog.tb_blog_info.blog_author</code>. 用户ID
	 */
	@Override
	public void setBlogAuthor(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>blog.tb_blog_info.blog_author</code>. 用户ID
	 */
	@NotNull
	@Override
	public Long getBlogAuthor() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>blog.tb_blog_info.blog_type</code>. 博客类型，0：未分类
	 */
	@Override
	public void setBlogType(Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>blog.tb_blog_info.blog_type</code>. 博客类型，0：未分类
	 */
	@NotNull
	@Override
	public Byte getBlogType() {
		return (Byte) getValue(2);
	}

	/**
	 * Setter for <code>blog.tb_blog_info.blog_title</code>. 文章标题
	 */
	@Override
	public void setBlogTitle(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>blog.tb_blog_info.blog_title</code>. 文章标题
	 */
	@NotNull
	@Size(max = 200)
	@Override
	public String getBlogTitle() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>blog.tb_blog_info.blog_abstract</code>. 文章摘要
	 */
	@Override
	public void setBlogAbstract(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>blog.tb_blog_info.blog_abstract</code>. 文章摘要
	 */
	@NotNull
	@Size(max = 500)
	@Override
	public String getBlogAbstract() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>blog.tb_blog_info.blog_content</code>. 文章内容
	 */
	@Override
	public void setBlogContent(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>blog.tb_blog_info.blog_content</code>. 文章内容
	 */
	@NotNull
	@Override
	public String getBlogContent() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>blog.tb_blog_info.created_time</code>. 创建时间
	 */
	@Override
	public void setCreatedTime(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>blog.tb_blog_info.created_time</code>. 创建时间
	 */
	@NotNull
	@Override
	public Timestamp getCreatedTime() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>blog.tb_blog_info.updated_time</code>. 更新时间
	 */
	@Override
	public void setUpdatedTime(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>blog.tb_blog_info.updated_time</code>. 更新时间
	 */
	@NotNull
	@Override
	public Timestamp getUpdatedTime() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>blog.tb_blog_info.comment_count</code>. 评论条数
	 */
	@Override
	public void setCommentCount(Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>blog.tb_blog_info.comment_count</code>. 评论条数
	 */
	@Override
	public Long getCommentCount() {
		return (Long) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<ULong> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<ULong, Long, Byte, String, String, String, Timestamp, Timestamp, Long> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<ULong, Long, Byte, String, String, String, Timestamp, Timestamp, Long> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<ULong> field1() {
		return TbBlogInfo.TB_BLOG_INFO.BLOG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TbBlogInfo.TB_BLOG_INFO.BLOG_AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field3() {
		return TbBlogInfo.TB_BLOG_INFO.BLOG_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TbBlogInfo.TB_BLOG_INFO.BLOG_TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TbBlogInfo.TB_BLOG_INFO.BLOG_ABSTRACT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TbBlogInfo.TB_BLOG_INFO.BLOG_CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return TbBlogInfo.TB_BLOG_INFO.CREATED_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return TbBlogInfo.TB_BLOG_INFO.UPDATED_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field9() {
		return TbBlogInfo.TB_BLOG_INFO.COMMENT_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ULong value1() {
		return getBlogId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getBlogAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value3() {
		return getBlogType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getBlogTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getBlogAbstract();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getBlogContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getCreatedTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getUpdatedTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value9() {
		return getCommentCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord value1(ULong value) {
		setBlogId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord value2(Long value) {
		setBlogAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord value3(Byte value) {
		setBlogType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord value4(String value) {
		setBlogTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord value5(String value) {
		setBlogAbstract(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord value6(String value) {
		setBlogContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord value7(Timestamp value) {
		setCreatedTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord value8(Timestamp value) {
		setUpdatedTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord value9(Long value) {
		setCommentCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TbBlogInfoRecord values(ULong value1, Long value2, Byte value3, String value4, String value5, String value6, Timestamp value7, Timestamp value8, Long value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ITbBlogInfo from) {
		setBlogId(from.getBlogId());
		setBlogAuthor(from.getBlogAuthor());
		setBlogType(from.getBlogType());
		setBlogTitle(from.getBlogTitle());
		setBlogAbstract(from.getBlogAbstract());
		setBlogContent(from.getBlogContent());
		setCreatedTime(from.getCreatedTime());
		setUpdatedTime(from.getUpdatedTime());
		setCommentCount(from.getCommentCount());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ITbBlogInfo> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TbBlogInfoRecord
	 */
	public TbBlogInfoRecord() {
		super(TbBlogInfo.TB_BLOG_INFO);
	}

	/**
	 * Create a detached, initialised TbBlogInfoRecord
	 */
	public TbBlogInfoRecord(ULong blogId, Long blogAuthor, Byte blogType, String blogTitle, String blogAbstract, String blogContent, Timestamp createdTime, Timestamp updatedTime, Long commentCount) {
		super(TbBlogInfo.TB_BLOG_INFO);

		setValue(0, blogId);
		setValue(1, blogAuthor);
		setValue(2, blogType);
		setValue(3, blogTitle);
		setValue(4, blogAbstract);
		setValue(5, blogContent);
		setValue(6, createdTime);
		setValue(7, updatedTime);
		setValue(8, commentCount);
	}
}
