/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.yanlz.blog.db.tables.UserInfo;
import org.yanlz.blog.db.tables.interfaces.IUserInfo;


/**
 * 用户基本信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> implements Record7<ULong, String, String, String, Timestamp, Timestamp, Byte>, IUserInfo {

	private static final long serialVersionUID = 2003021388;

	/**
	 * Setter for <code>blog.tb_user_info.user_id</code>. 主键
	 */
	@Override
	public void setUserId(ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>blog.tb_user_info.user_id</code>. 主键
	 */
	@NotNull
	@Override
	public ULong getUserId() {
		return (ULong) getValue(0);
	}

	/**
	 * Setter for <code>blog.tb_user_info.nick_name</code>. 用户昵称
	 */
	@Override
	public void setNickName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>blog.tb_user_info.nick_name</code>. 用户昵称
	 */
	@NotNull
	@Size(max = 30)
	@Override
	public String getNickName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>blog.tb_user_info.protrait_url</code>. 头像地址
	 */
	@Override
	public void setProtraitUrl(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>blog.tb_user_info.protrait_url</code>. 头像地址
	 */
	@NotNull
	@Size(max = 200)
	@Override
	public String getProtraitUrl() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>blog.tb_user_info.telephone</code>. 电话
	 */
	@Override
	public void setTelephone(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>blog.tb_user_info.telephone</code>. 电话
	 */
	@NotNull
	@Size(max = 15)
	@Override
	public String getTelephone() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>blog.tb_user_info.created_time</code>. 创建时间
	 */
	@Override
	public void setCreatedTime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>blog.tb_user_info.created_time</code>. 创建时间
	 */
	@NotNull
	@Override
	public Timestamp getCreatedTime() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>blog.tb_user_info.updated_time</code>. 修改时间
	 */
	@Override
	public void setUpdatedTime(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>blog.tb_user_info.updated_time</code>. 修改时间
	 */
	@NotNull
	@Override
	public Timestamp getUpdatedTime() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>blog.tb_user_info.status</code>. 账户状态，枚举类型，0:无效，1:有效，默认为1
	 */
	@Override
	public void setStatus(Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>blog.tb_user_info.status</code>. 账户状态，枚举类型，0:无效，1:有效，默认为1
	 */
	@NotNull
	@Override
	public Byte getStatus() {
		return (Byte) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<ULong> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<ULong, String, String, String, Timestamp, Timestamp, Byte> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<ULong, String, String, String, Timestamp, Timestamp, Byte> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<ULong> field1() {
		return UserInfo.TB_USER_INFO.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return UserInfo.TB_USER_INFO.NICK_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return UserInfo.TB_USER_INFO.PROTRAIT_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return UserInfo.TB_USER_INFO.TELEPHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return UserInfo.TB_USER_INFO.CREATED_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return UserInfo.TB_USER_INFO.UPDATED_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field7() {
		return UserInfo.TB_USER_INFO.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ULong value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNickName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getProtraitUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getTelephone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getCreatedTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getUpdatedTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value7() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfoRecord value1(ULong value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfoRecord value2(String value) {
		setNickName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfoRecord value3(String value) {
		setProtraitUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfoRecord value4(String value) {
		setTelephone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfoRecord value5(Timestamp value) {
		setCreatedTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfoRecord value6(Timestamp value) {
		setUpdatedTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfoRecord value7(Byte value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfoRecord values(ULong value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, Byte value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IUserInfo from) {
		setUserId(from.getUserId());
		setNickName(from.getNickName());
		setProtraitUrl(from.getProtraitUrl());
		setTelephone(from.getTelephone());
		setCreatedTime(from.getCreatedTime());
		setUpdatedTime(from.getUpdatedTime());
		setStatus(from.getStatus());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IUserInfo> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserInfoRecord
	 */
	public UserInfoRecord() {
		super(UserInfo.TB_USER_INFO);
	}

	/**
	 * Create a detached, initialised UserInfoRecord
	 */
	public UserInfoRecord(ULong userId, String nickName, String protraitUrl, String telephone, Timestamp createdTime, Timestamp updatedTime, Byte status) {
		super(UserInfo.TB_USER_INFO);

		setValue(0, userId);
		setValue(1, nickName);
		setValue(2, protraitUrl);
		setValue(3, telephone);
		setValue(4, createdTime);
		setValue(5, updatedTime);
		setValue(6, status);
	}
}
