/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.yanlz.blog.db.Blog;
import org.yanlz.blog.db.Keys;
import org.yanlz.blog.db.tables.records.UserInfoRecord;


/**
 * 用户基本信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo extends TableImpl<UserInfoRecord> {

	private static final long serialVersionUID = -1920677669;

	/**
	 * The reference instance of <code>blog.tb_user_info</code>
	 */
	public static final UserInfo TB_USER_INFO = new UserInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserInfoRecord> getRecordType() {
		return UserInfoRecord.class;
	}

	/**
	 * The column <code>blog.tb_user_info.user_id</code>. 主键
	 */
	public final TableField<UserInfoRecord, ULong> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "主键");

	/**
	 * The column <code>blog.tb_user_info.nick_name</code>. 用户昵称
	 */
	public final TableField<UserInfoRecord, String> NICK_NAME = createField("nick_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaulted(true), this, "用户昵称");

	/**
	 * The column <code>blog.tb_user_info.protrait_url</code>. 头像地址
	 */
	public final TableField<UserInfoRecord, String> PROTRAIT_URL = createField("protrait_url", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false).defaulted(true), this, "头像地址");

	/**
	 * The column <code>blog.tb_user_info.telephone</code>. 电话
	 */
	public final TableField<UserInfoRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false).defaulted(true), this, "电话");

	/**
	 * The column <code>blog.tb_user_info.created_time</code>. 创建时间
	 */
	public final TableField<UserInfoRecord, Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "创建时间");

	/**
	 * The column <code>blog.tb_user_info.updated_time</code>. 修改时间
	 */
	public final TableField<UserInfoRecord, Timestamp> UPDATED_TIME = createField("updated_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "修改时间");

	/**
	 * The column <code>blog.tb_user_info.status</code>. 账户状态，枚举类型，0:无效，1:有效，默认为1
	 */
	public final TableField<UserInfoRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "账户状态，枚举类型，0:无效，1:有效，默认为1");

	/**
	 * Create a <code>blog.tb_user_info</code> table reference
	 */
	public UserInfo() {
		this("tb_user_info", null);
	}

	/**
	 * Create an aliased <code>blog.tb_user_info</code> table reference
	 */
	public UserInfo(String alias) {
		this(alias, TB_USER_INFO);
	}

	private UserInfo(String alias, Table<UserInfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserInfo(String alias, Table<UserInfoRecord> aliased, Field<?>[] parameters) {
		super(alias, Blog.BLOG, aliased, parameters, "用户基本信息表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<UserInfoRecord, ULong> getIdentity() {
		return Keys.IDENTITY_TB_USER_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserInfoRecord> getPrimaryKey() {
		return Keys.KEY_TB_USER_INFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserInfoRecord>> getKeys() {
		return Arrays.<UniqueKey<UserInfoRecord>>asList(Keys.KEY_TB_USER_INFO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfo as(String alias) {
		return new UserInfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserInfo rename(String name) {
		return new UserInfo(name, null);
	}
}
