/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.yanlz.blog.db.tables.Account;
import org.yanlz.blog.db.tables.BlogInfo;
import org.yanlz.blog.db.tables.CommentInfo;
import org.yanlz.blog.db.tables.UserInfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blog extends SchemaImpl {

	private static final long serialVersionUID = -1258904334;

	/**
	 * The reference instance of <code>blog</code>
	 */
	public static final Blog BLOG = new Blog();

	/**
	 * No further instances allowed
	 */
	private Blog() {
		super("blog");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Account.TB_ACCOUNT,
			BlogInfo.TB_BLOG_INFO,
			CommentInfo.TB_COMMENT_INFO,
			UserInfo.TB_USER_INFO);
	}
}
