/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db;


import javax.annotation.Generated;

import org.yanlz.blog.db.tables.TbAccount;
import org.yanlz.blog.db.tables.TbBlogInfo;
import org.yanlz.blog.db.tables.TbCommentInfo;
import org.yanlz.blog.db.tables.TbUserInfo;


/**
 * Convenience access to all tables in blog
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * 用户账户表
	 */
	public static final TbAccount TB_ACCOUNT = org.yanlz.blog.db.tables.TbAccount.TB_ACCOUNT;

	/**
	 * 文章信息表
	 */
	public static final TbBlogInfo TB_BLOG_INFO = org.yanlz.blog.db.tables.TbBlogInfo.TB_BLOG_INFO;

	/**
	 * 评论信息表
	 */
	public static final TbCommentInfo TB_COMMENT_INFO = org.yanlz.blog.db.tables.TbCommentInfo.TB_COMMENT_INFO;

	/**
	 * 用户基本信息表
	 */
	public static final TbUserInfo TB_USER_INFO = org.yanlz.blog.db.tables.TbUserInfo.TB_USER_INFO;
}
