/**
 * This class is generated by jOOQ
 */
package org.yanlz.blog.db;


import javax.annotation.Generated;

import org.yanlz.blog.db.tables.Account;
import org.yanlz.blog.db.tables.BlogInfo;
import org.yanlz.blog.db.tables.CommentInfo;
import org.yanlz.blog.db.tables.UserInfo;


/**
 * Convenience access to all tables in blog
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * 用户账户表
	 */
	public static final Account TB_ACCOUNT = org.yanlz.blog.db.tables.Account.TB_ACCOUNT;

	/**
	 * 文章信息表
	 */
	public static final BlogInfo TB_BLOG_INFO = org.yanlz.blog.db.tables.BlogInfo.TB_BLOG_INFO;

	/**
	 * 评论信息表
	 */
	public static final CommentInfo TB_COMMENT_INFO = org.yanlz.blog.db.tables.CommentInfo.TB_COMMENT_INFO;

	/**
	 * 用户基本信息表
	 */
	public static final UserInfo TB_USER_INFO = org.yanlz.blog.db.tables.UserInfo.TB_USER_INFO;
}
